settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: robo all-build-local
      run:
        status: true
        method: ./docker/api/bin/api-server
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .idea
        - logs
        - docker
