version: '3.7'
services:
  app:
    build:
      context: "."
      dockerfile: "./docker/api/Dockerfile"
      target: build
    ports:
      - '3000:3000'
    volumes:
      - '.:/go/src/github.com/yyh-gl/hobigon-golang-api-server'
    command: ["sh", "-c", "realize start --run"]
    environment:
      APP_ENV: "develop"
      GO111MODULE: "on"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "hobigon"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "mysql"
      LOG_PATH: "./logs"
    depends_on:
      - db
  db:
    image: mysql:8.0.17
    ports:
      - '13306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
